# Generated by Django 4.2.2 on 2023-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_emp_id_emp_emp_id1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
